apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: omaraliii1/ecommerce:product
        ports:
        - containerPort: 5002
        env:
        - name: SQLALCHEMY_DATABASE_URI
          value: "postgresql://postgres:1234@postgres:5432/cloud"
        - name: SECRET_KEY
          value: test123
---
apiVersion: v1
kind: Service
metadata:
  name: product
  labels:
    app: product
spec:
  type: NodePort
  ports:
    - port: 5002
      targetPort: 5002
      nodePort: 30004
  selector:
    app: product

